export { default as ProfileStats } from './ProfileStats.vue'
export { default as DailyNutritionStats } from './DailyNutritionStats.vue'
export { default as MealsList } from './MealsList.vue'

export { default as CryptoPayment } from './PaymentView.vue'
export { default as PaymentMethod } from './PaymentMethod.vue'
export { default as SubscriptionPlan } from './SubscriptionPlan.vue'
export { default as PaymentsList } from './PaymentsList.vue'
export { default as StatisticsTab } from './StatisticsTab.vue'
export { default as WeightInput } from './WeightInput.vue'
